/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkflowTemplatesRouteImport } from './routes/workflow-templates'
import { Route as WasteRouteImport } from './routes/waste'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RecallsRouteImport } from './routes/recalls'
import { Route as RawMaterialsRouteImport } from './routes/raw-materials'
import { Route as QualityControlRouteImport } from './routes/quality-control'
import { Route as ProductionPlanningRouteImport } from './routes/production-planning'
import { Route as ProductionBatchesRouteImport } from './routes/production-batches'
import { Route as PackagingRouteImport } from './routes/packaging'
import { Route as FinishedGoodsRouteImport } from './routes/finished-goods'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CustomerReceivingRouteImport } from './routes/customer-receiving'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesEditorRouteImport } from './routes/recipes_.editor'
import { Route as PackagingNewRouteImport } from './routes/packaging_.new'
import { Route as ProductionBatchesRunBatchIdRouteImport } from './routes/production-batches_.run.$batchId'
import { Route as PackagingRunRunIdRouteImport } from './routes/packaging_.run.$runId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowTemplatesRoute = WorkflowTemplatesRouteImport.update({
  id: '/workflow-templates',
  path: '/workflow-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const WasteRoute = WasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallsRoute = RecallsRouteImport.update({
  id: '/recalls',
  path: '/recalls',
  getParentRoute: () => rootRouteImport,
} as any)
const RawMaterialsRoute = RawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityControlRoute = QualityControlRouteImport.update({
  id: '/quality-control',
  path: '/quality-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionPlanningRoute = ProductionPlanningRouteImport.update({
  id: '/production-planning',
  path: '/production-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionBatchesRoute = ProductionBatchesRouteImport.update({
  id: '/production-batches',
  path: '/production-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingRoute = PackagingRouteImport.update({
  id: '/packaging',
  path: '/packaging',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishedGoodsRoute = FinishedGoodsRouteImport.update({
  id: '/finished-goods',
  path: '/finished-goods',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerReceivingRoute = CustomerReceivingRouteImport.update({
  id: '/customer-receiving',
  path: '/customer-receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesEditorRoute = RecipesEditorRouteImport.update({
  id: '/recipes_/editor',
  path: '/recipes/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingNewRoute = PackagingNewRouteImport.update({
  id: '/packaging_/new',
  path: '/packaging/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionBatchesRunBatchIdRoute =
  ProductionBatchesRunBatchIdRouteImport.update({
    id: '/production-batches_/run/$batchId',
    path: '/production-batches/run/$batchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PackagingRunRunIdRoute = PackagingRunRunIdRouteImport.update({
  id: '/packaging_/run/$runId',
  path: '/packaging/run/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/company': typeof CompanyRoute
  '/customer-receiving': typeof CustomerReceivingRoute
  '/dispatch': typeof DispatchRoute
  '/finished-goods': typeof FinishedGoodsRoute
  '/packaging': typeof PackagingRoute
  '/production-batches': typeof ProductionBatchesRoute
  '/production-planning': typeof ProductionPlanningRoute
  '/quality-control': typeof QualityControlRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/recalls': typeof RecallsRoute
  '/recipes': typeof RecipesRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/storage': typeof StorageRoute
  '/suppliers': typeof SuppliersRoute
  '/traceability': typeof TraceabilityRoute
  '/verify': typeof VerifyRoute
  '/waste': typeof WasteRoute
  '/workflow-templates': typeof WorkflowTemplatesRoute
  '/workflows': typeof WorkflowsRoute
  '/packaging/new': typeof PackagingNewRoute
  '/recipes/editor': typeof RecipesEditorRoute
  '/packaging/run/$runId': typeof PackagingRunRunIdRoute
  '/production-batches/run/$batchId': typeof ProductionBatchesRunBatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/company': typeof CompanyRoute
  '/customer-receiving': typeof CustomerReceivingRoute
  '/dispatch': typeof DispatchRoute
  '/finished-goods': typeof FinishedGoodsRoute
  '/packaging': typeof PackagingRoute
  '/production-batches': typeof ProductionBatchesRoute
  '/production-planning': typeof ProductionPlanningRoute
  '/quality-control': typeof QualityControlRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/recalls': typeof RecallsRoute
  '/recipes': typeof RecipesRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/storage': typeof StorageRoute
  '/suppliers': typeof SuppliersRoute
  '/traceability': typeof TraceabilityRoute
  '/verify': typeof VerifyRoute
  '/waste': typeof WasteRoute
  '/workflow-templates': typeof WorkflowTemplatesRoute
  '/workflows': typeof WorkflowsRoute
  '/packaging/new': typeof PackagingNewRoute
  '/recipes/editor': typeof RecipesEditorRoute
  '/packaging/run/$runId': typeof PackagingRunRunIdRoute
  '/production-batches/run/$batchId': typeof ProductionBatchesRunBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/company': typeof CompanyRoute
  '/customer-receiving': typeof CustomerReceivingRoute
  '/dispatch': typeof DispatchRoute
  '/finished-goods': typeof FinishedGoodsRoute
  '/packaging': typeof PackagingRoute
  '/production-batches': typeof ProductionBatchesRoute
  '/production-planning': typeof ProductionPlanningRoute
  '/quality-control': typeof QualityControlRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/recalls': typeof RecallsRoute
  '/recipes': typeof RecipesRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/storage': typeof StorageRoute
  '/suppliers': typeof SuppliersRoute
  '/traceability': typeof TraceabilityRoute
  '/verify': typeof VerifyRoute
  '/waste': typeof WasteRoute
  '/workflow-templates': typeof WorkflowTemplatesRoute
  '/workflows': typeof WorkflowsRoute
  '/packaging_/new': typeof PackagingNewRoute
  '/recipes_/editor': typeof RecipesEditorRoute
  '/packaging_/run/$runId': typeof PackagingRunRunIdRoute
  '/production-batches_/run/$batchId': typeof ProductionBatchesRunBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/company'
    | '/customer-receiving'
    | '/dispatch'
    | '/finished-goods'
    | '/packaging'
    | '/production-batches'
    | '/production-planning'
    | '/quality-control'
    | '/raw-materials'
    | '/recalls'
    | '/recipes'
    | '/reports'
    | '/returns'
    | '/storage'
    | '/suppliers'
    | '/traceability'
    | '/verify'
    | '/waste'
    | '/workflow-templates'
    | '/workflows'
    | '/packaging/new'
    | '/recipes/editor'
    | '/packaging/run/$runId'
    | '/production-batches/run/$batchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/company'
    | '/customer-receiving'
    | '/dispatch'
    | '/finished-goods'
    | '/packaging'
    | '/production-batches'
    | '/production-planning'
    | '/quality-control'
    | '/raw-materials'
    | '/recalls'
    | '/recipes'
    | '/reports'
    | '/returns'
    | '/storage'
    | '/suppliers'
    | '/traceability'
    | '/verify'
    | '/waste'
    | '/workflow-templates'
    | '/workflows'
    | '/packaging/new'
    | '/recipes/editor'
    | '/packaging/run/$runId'
    | '/production-batches/run/$batchId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/company'
    | '/customer-receiving'
    | '/dispatch'
    | '/finished-goods'
    | '/packaging'
    | '/production-batches'
    | '/production-planning'
    | '/quality-control'
    | '/raw-materials'
    | '/recalls'
    | '/recipes'
    | '/reports'
    | '/returns'
    | '/storage'
    | '/suppliers'
    | '/traceability'
    | '/verify'
    | '/waste'
    | '/workflow-templates'
    | '/workflows'
    | '/packaging_/new'
    | '/recipes_/editor'
    | '/packaging_/run/$runId'
    | '/production-batches_/run/$batchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CompanyRoute: typeof CompanyRoute
  CustomerReceivingRoute: typeof CustomerReceivingRoute
  DispatchRoute: typeof DispatchRoute
  FinishedGoodsRoute: typeof FinishedGoodsRoute
  PackagingRoute: typeof PackagingRoute
  ProductionBatchesRoute: typeof ProductionBatchesRoute
  ProductionPlanningRoute: typeof ProductionPlanningRoute
  QualityControlRoute: typeof QualityControlRoute
  RawMaterialsRoute: typeof RawMaterialsRoute
  RecallsRoute: typeof RecallsRoute
  RecipesRoute: typeof RecipesRoute
  ReportsRoute: typeof ReportsRoute
  ReturnsRoute: typeof ReturnsRoute
  StorageRoute: typeof StorageRoute
  SuppliersRoute: typeof SuppliersRoute
  TraceabilityRoute: typeof TraceabilityRoute
  VerifyRoute: typeof VerifyRoute
  WasteRoute: typeof WasteRoute
  WorkflowTemplatesRoute: typeof WorkflowTemplatesRoute
  WorkflowsRoute: typeof WorkflowsRoute
  PackagingNewRoute: typeof PackagingNewRoute
  RecipesEditorRoute: typeof RecipesEditorRoute
  PackagingRunRunIdRoute: typeof PackagingRunRunIdRoute
  ProductionBatchesRunBatchIdRoute: typeof ProductionBatchesRunBatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-templates': {
      id: '/workflow-templates'
      path: '/workflow-templates'
      fullPath: '/workflow-templates'
      preLoaderRoute: typeof WorkflowTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waste': {
      id: '/waste'
      path: '/waste'
      fullPath: '/waste'
      preLoaderRoute: typeof WasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recalls': {
      id: '/recalls'
      path: '/recalls'
      fullPath: '/recalls'
      preLoaderRoute: typeof RecallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-materials': {
      id: '/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof RawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-control': {
      id: '/quality-control'
      path: '/quality-control'
      fullPath: '/quality-control'
      preLoaderRoute: typeof QualityControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-planning': {
      id: '/production-planning'
      path: '/production-planning'
      fullPath: '/production-planning'
      preLoaderRoute: typeof ProductionPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-batches': {
      id: '/production-batches'
      path: '/production-batches'
      fullPath: '/production-batches'
      preLoaderRoute: typeof ProductionBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging': {
      id: '/packaging'
      path: '/packaging'
      fullPath: '/packaging'
      preLoaderRoute: typeof PackagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finished-goods': {
      id: '/finished-goods'
      path: '/finished-goods'
      fullPath: '/finished-goods'
      preLoaderRoute: typeof FinishedGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-receiving': {
      id: '/customer-receiving'
      path: '/customer-receiving'
      fullPath: '/customer-receiving'
      preLoaderRoute: typeof CustomerReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes_/editor': {
      id: '/recipes_/editor'
      path: '/recipes/editor'
      fullPath: '/recipes/editor'
      preLoaderRoute: typeof RecipesEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging_/new': {
      id: '/packaging_/new'
      path: '/packaging/new'
      fullPath: '/packaging/new'
      preLoaderRoute: typeof PackagingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-batches_/run/$batchId': {
      id: '/production-batches_/run/$batchId'
      path: '/production-batches/run/$batchId'
      fullPath: '/production-batches/run/$batchId'
      preLoaderRoute: typeof ProductionBatchesRunBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging_/run/$runId': {
      id: '/packaging_/run/$runId'
      path: '/packaging/run/$runId'
      fullPath: '/packaging/run/$runId'
      preLoaderRoute: typeof PackagingRunRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CompanyRoute: CompanyRoute,
  CustomerReceivingRoute: CustomerReceivingRoute,
  DispatchRoute: DispatchRoute,
  FinishedGoodsRoute: FinishedGoodsRoute,
  PackagingRoute: PackagingRoute,
  ProductionBatchesRoute: ProductionBatchesRoute,
  ProductionPlanningRoute: ProductionPlanningRoute,
  QualityControlRoute: QualityControlRoute,
  RawMaterialsRoute: RawMaterialsRoute,
  RecallsRoute: RecallsRoute,
  RecipesRoute: RecipesRoute,
  ReportsRoute: ReportsRoute,
  ReturnsRoute: ReturnsRoute,
  StorageRoute: StorageRoute,
  SuppliersRoute: SuppliersRoute,
  TraceabilityRoute: TraceabilityRoute,
  VerifyRoute: VerifyRoute,
  WasteRoute: WasteRoute,
  WorkflowTemplatesRoute: WorkflowTemplatesRoute,
  WorkflowsRoute: WorkflowsRoute,
  PackagingNewRoute: PackagingNewRoute,
  RecipesEditorRoute: RecipesEditorRoute,
  PackagingRunRunIdRoute: PackagingRunRunIdRoute,
  ProductionBatchesRunBatchIdRoute: ProductionBatchesRunBatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
